version: "3.8"
services:
  nsp_backend:
    container_name: nsp_backend
    build:
      context: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - nsp_db
  nsp_db:
    container_name: nsp_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - nps_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    container_name: tcit_frontend
    volumes:
      - ./frontend:/opt
    
volumes:
  nps_data: {}